# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YOUTUBE COPY' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YOUTUBE COPY
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 4.3'
end
